language: haskell

install:
    - cabal install mega-sdist hspec cabal-meta cabal-src
    - cabal-meta install --force-reinstalls

script: mega-sdist --test

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
  email: true

